services:
  postgres: # Garde le nom postgres
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: pmtdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: spring_backend
    restart: always
    depends_on:
      - postgres # Utilise postgres ici
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pmtdb # Change db -> postgres
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  postgres_data:
