server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/pmtdatabase
    driverClassName: org.postgresql.Driver
    username: myuser
    password: mypassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
